{"name": "test_eval[7*5-30]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 35 == 30\n  -35\n  +30", "trace": "test_input = '7*5', expected = 30\n\n    @pytest.mark.parametrize(\"test_input,expected\", [(\"3+5\",8),\n                                                     (\"2-1\",1),\n                                                     (\"7*5\",30),\n                                                     ])\n    def test_eval(test_input, expected):\n>       assert eval(test_input) == expected\nE       assert 35 == 30\nE         -35\nE         +30\n\ntest_params.py:12: AssertionError"}, "parameters": [{"name": "test_input", "value": "'7*5'"}, {"name": "expected", "value": "30"}], "start": 1593423821989, "stop": 1593423821990, "uuid": "898ade47-2c43-471f-8cda-09cc0ef76ae2", "historyId": "eebad7a44869eefccbbf5fbff106e4c4", "testCaseId": "271a0b451b05f1f4273bc695f760faf0", "fullName": "test_params#test_eval", "labels": [{"name": "suite", "value": "test_params"}, {"name": "host", "value": "DESKTOP-DN3J7GJ"}, {"name": "thread", "value": "3372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_params"}]}